version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "17:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: scope
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      include: scope
  - package-ecosystem: pip
    directory: "/"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    schedule:
      interval: weekly
      day: friday
      time: "17:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
