version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "17:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - davidlday
