name: Autoapprove PRs
on: pull_request

permissions:
  pull-requests: write

jobs:
  autoapprove-prs:
    uses: prosegrinder/.github/.github/workflows/autoapprove-prs.yaml@main
    with:
      PR_URL: ${{github.event.pull_request.html_url}}
    secrets:
      APPROVAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
