name: Bump, Release, and Publish

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      newversion:
        description: "Bump Type (major minor patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      testpublish:
        description: "Publish to TestPypi"
        default: false
        type: boolean

concurrency:
  group: tag-and-release
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Bump Version
        run: poetry version ${{ github.event.inputs.newversion }}
      - name: Get New Version
        id: get-new-version
        run: |
          echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: poetry install --with dev --no-interaction --no-root
      - name: Install project
        run: poetry install --with dev --no-interaction
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
      - name: Poetry Build
        run: |
          poetry build
      - name: Poetry Publish to PyPi Test
        if: ${{ 'true' == github.event.inputs.testpublish }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --repository testpypi --no-interaction --skip-existing
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Poetry Publish to PyPi
        run: |
          poetry publish --no-interaction
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      - name: Commit and Push
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email 'david@davidlday.com'
          git add ./pyproject.toml
          git commit -m "[skip ci] bumped version to ${{ steps.get-new-version.version }}"
          git push
      - name: Tag version
        id: tag-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.get-new-version.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag-version.outputs.new_tag }}
          name: ${{ steps.tag-version.outputs.new_tag }}
          body: ${{ steps.tag-version.outputs.changelog }}
