name: Publish to PyPi

on:
  push:
    tags:
      - "v*"

jobs:
  black:
    uses: prosegrinder/.github/.github/workflows/poetry-black.yaml@main

  pylint:
    uses: prosegrinder/.github/.github/workflows/poetry-pylint.yaml@main

  mypy:
    uses: prosegrinder/.github/.github/workflows/poetry-mypy.yaml@main

  bandit:
    uses: prosegrinder/.github/.github/workflows/poetry-bandit.yaml@main

  test:
    needs:
      - pylint
      - black
      - mypy
      - bandit
    uses: prosegrinder/.github/.github/workflows/poetry-test.yaml@main

  publish:
    needs: test
    uses: prosegrinder/.github/.github/workflows/poetry-publish.yaml@main
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
