name: Publish to PyPi

on:
  push:
    tags:
      - "v*"

jobs:
  lint:
    uses: prosegrinder/.github/.github/workflows/poetry-lint.yaml@main

  test:
    needs: lint
    uses: prosegrinder/.github/.github/workflows/poetry-test.yaml@main

  publish:
    needs: test
    uses: prosegrinder/.github/.github/workflows/poetry-publish.yaml@main
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
