name: Python Poetry CI

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: prosegrinder/.github/.github/workflows/poetry-lint.yaml@main

  test:
    needs: lint
    uses: prosegrinder/.github/.github/workflows/poetry-test.yaml@main

  cz-dry-run:
    needs: test
    name: "Dry run Commitizen bump"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.18.2
        with:
          github_token: ${{ secrets.VERSION_BUMP_TAG_TOKEN }}
          check_consistency: true
          dry_run: true
