name: Python Poetry CI

permissions:
  contents: read

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  black:
    uses: prosegrinder/.github/.github/workflows/poetry-black.yaml@main

  pylint:
    uses: prosegrinder/.github/.github/workflows/poetry-pylint.yaml@main

  mypy:
    uses: prosegrinder/.github/.github/workflows/poetry-mypy.yaml@main

  bandit:
    uses: prosegrinder/.github/.github/workflows/poetry-bandit.yaml@main

  test:
    needs:
      - pylint
      - black
      - mypy
      - bandit
    uses: prosegrinder/.github/.github/workflows/poetry-test.yaml@main

  cz-dry-run:
    needs: test
    name: "Dry run Commitizen bump"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_consistency: true
          dry_run: true
